[placeholders.board]
type = "string"
prompt = "Which board do you use?"
choices = [
  "Niti V1 Board",
  "Arduino Mega 2560",
  "Arduino Mega 1280",
  "Arduino Nano",
  "Arduino Nano New Bootloader",
  "Arduino Uno",
  "Nano168",
]
default = "Niti V1 Board"

[template]
ignore=["README.md"]

[hooks]
post = ["rename-readme.delta"]
