[placeholders.board]
type = "string"
prompt = "Which board do you use 😎?"
choices = [
  "Niti V1",
  "Arduino Mega 2560",
  "Arduino Nano",
  "Arduino Nano New Bootloader",
  "Arduino Uno",
]
default = "Niti V1"

[template]
ignore=["README.md"]

[hooks]
post = ["rename-readme.jelabi"]
