[build]
{% case board -%}
  {%- when "Niti V1 Board" -%}
    target = "avr-specs/niti-v1.json"
  {%- when "Arduino Mega 2560" -%}
    target = "avr-specs/avr-atmega2560.json"
  {%- when "Arduino Nano" -%}
    target = "avr-specs/avr-atmega328p.json"
  {%- when "Arduino Nano New Bootloader" -%}
    target = "avr-specs/avr-atmega328p.json"
  {%- when "Arduino Uno" -%}
    target = "avr-specs/avr-atmega328p.json"
  {%- when "Nano168" -%}
    target = "avr-specs/avr-atmega168.json"
{%- endcase %}

[target.'cfg(target_arch = "avr")']
{% case board -%}
  {%- when "Niti V1 Board" -%}
    runner = "waterman nitiv1 -cb 57600"
  {%- when "Arduino Mega 2560" -%}
    runner = "waterman mega2560 -cb 57600"
  {%- when "Arduino Nano" -%}
    runner = "waterman nano -cb 57600"
  {%- when "Arduino Nano New Bootloader" -%}
    runner = "waterman nano-new -cb 57600"
  {%- when "Arduino Uno" -%}
    runner = "waterman uno -cb 57600"
  {%- when "Nano168" -%}
    runner = "waterman nano168 -cb 57600"
{%- endcase %}

[unstable]
build-std = ["core"]
{%- comment %}
# vim: ft=toml.jinja2
{% endcomment %}
